# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mottoui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 523)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 831, 491))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("CorruptLinearElk-size_restricted.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 150, 141, 81))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("font: italic 14pt \"Franklin Gothic Heavy\";\n"
"background-color: rgb(6, 54, 187);")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, -30, 471, 371))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("new_updated_logo.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(520, 10, 141, 51))
        self.textBrowser_2.setStyleSheet("font: 11pt \"Franklin Gothic Heavy\";\n"


                                         "background:transparent;\n"
                                         "border-radius:none;\n"
                                         "color:white;\n"
                                         "font-size:20px;")

        self.textBrowser_2.setObjectName("textBrowser_2")

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(525, 150, 141, 81))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("font: italic 14pt \"Franklin Gothic Heavy\";\n"
"background-color: rgb(213, 0, 0);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 240, 561, 91))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D4Ll.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")

        self.textBrowser_69 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_69.setGeometry(QtCore.QRect(110, 350, 500, 100))
        self.textBrowser_69.setStyleSheet("font: 11pt \"Franklin Gothic Heavy\";\n"
                                         "background:transparent;\n"
                                         "border-radius:none;\n"
                                         "color:white;\n"
                                         "font-size:20px;")

        self.textBrowser_69.setObjectName("textBrowser_69")

        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(520, 50, 141, 51))
        self.textBrowser_3.setStyleSheet("font: 11pt \"Franklin Gothic Heavy\";\n"
"background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label.raise_()
        self.label_2.raise_()
        self.textBrowser_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.textBrowser_69.raise_()
        self.textBrowser_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "RUN"))
        self.pushButton_3.setText(_translate("MainWindow", "TERMINATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
